### ISSUE TITLE
cs2.exe - Entry point not found

### ISSUE THREAD

**Issue by BnanZ0** [Source2ZE/CS2ServerGUI#3]
The procedure entry point _AssertValidReadPtr could not be located in the dynamic link library.
![螢幕擷取畫面 2024-11-13 125258](https://github.com/user-attachments/assets/a67056f9-fc33-4893-a3b1-672063dd6529)

**Comment by Vauff** [comment]
Fixed in https://github.com/Source2ZE/CS2ServerGUI/commit/736967fa1dadbd00389db03fb5b18e58a6242a14 https://github.com/Source2ZE/CS2ServerGUI/releases/tag/v1.0.3
